### ISSUE TITLE
Busboy or firebase error

### ISSUE THREAD

**Issue by Johnny1500** [hidjou/classsed-react-firebase-functions#8]
When I am trying to upload an image to Firestore I get an error in cloud firestore's dashboard: 
Error: Failed to import the Cloud Storage client library for Node.js. Make sure to install the "@google-cloud/storage" npm package. Original error: Error: Cannot find module 'ent'
    at new FirebaseError (/srv/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at new Storage (/srv/node_modules/firebase-admin/lib/storage/storage.js:60:19)
    at /srv/node_modules/firebase-admin/lib/firebase-app.js:254:20
    at FirebaseApp.ensureService_ (/srv/node_modules/firebase-admin/lib/firebase-app.js:339:23)
    at FirebaseApp.storage (/srv/node_modules/firebase-admin/lib/firebase-app.js:252:21)
    at FirebaseNamespace.fn (/srv/node_modules/firebase-admin/lib/firebase-namespace.js:311:45)
    at Busboy.busboy.on (/srv/handlers/users.js:226:8)
    at emitNone (events.js:106:13)
    at Busboy.emit (events.js:208:7)
    at Busboy.emit (/srv/node_modules/busboy/lib/main.js:37:33)
I have the same code."npm i -g @google-cloud/storage" didn't help.
What's wrong?

**Comment by enterpinamullah** [comment]
if you still need help, then I can help if you show me your code in the users.js file line 226

**Comment by Johnny1500** [comment]
Thanks, I resolved the issue.

пт, 15 мая 2020 г. в 02:41, InamullahICP <notifications@github.com>:
